# Generated by Django 4.1.4 on 2022-12-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='active_listings',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
