# Generated by Django 4.1.4 on 2023-01-05 05:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='pfp',
            field=models.ImageField(null=True, upload_to=accounts.models.dp),
        ),
    ]
