# Generated by Django 4.1.4 on 2023-01-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_post_id'),
        ('user', '0003_rename_likes_like'),
    ]

    operations = [
    ]
